import { Category, MenuItem, RestaurantSettings } from './types';

export const DEFAULT_CATEGORIES: Category[] = [
  { id: 'all', name: 'All Appétit', icon: 'Sparkles' },
  { id: 'burgers', name: 'Burgers', icon: 'Beef' },
  { id: 'chicken-burgers', name: 'Chicken Burgers', icon: 'CheckSquare' }, // Fallback icon or custom rendered
  { id: 'fries', name: 'Fries', icon: 'Container' },
  { id: 'milkshakes', name: 'Milkshakes', icon: 'CupSoda' },
  { id: 'soft-drinks', name: 'Soft Drinks', icon: 'Droplet' },
  { id: 'desserts', name: 'Desserts', icon: 'Cake' }
];

export const DEFAULT_MENU_ITEMS: MenuItem[] = [
  {
    id: '1',
    name: 'Classic Beef Burger',
    category: 'burgers',
    description: 'Juicy prime local beef patty, nested in toasted artisanal brioche, layered with fresh lettuce, farm tomatoes, sweet red onions, and our signature secret Wow House Sauce.',
    ingredients: ['100% Local Prime Beef', 'Artisanal Brioche Bun', 'Romaine Lettuce', 'Beefsteak Tomato', 'Red Onion', 'Secret Wow Sauce'],
    calories: '650 kcal',
    protein: '34g',
    carbs: '42g',
    fat: '28g',
    price: 450,
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&q=80&w=800',
    available: true,
    featured: true
  },
  {
    id: '2',
    name: 'Double Cheese Burger',
    category: 'burgers',
    description: 'Two flame-grilled beef patties, double golden melted cheddar, tangy pickled slices, caramelized onions, and house mustard mayo. Intense cheese-packed goodness.',
    ingredients: ['Double Beef Patty', 'Double Cheddar Cheese', 'Brioche Bun', 'Caramelized Onions', 'Dill Pickles', 'Mustard Mayo Sauce'],
    calories: '920 kcal',
    protein: '58g',
    carbs: '45g',
    fat: '48g',
    price: 550,
    image: 'https://images.unsplash.com/photo-1571091718767-18b5b1457add?auto=format&fit=crop&q=80&w=800',
    available: true,
    featured: true
  },
  {
    id: '3',
    name: 'Bole Special Burger',
    category: 'burgers',
    description: 'The pride of Bole! Premium beef patty, crispy beef bacon, fried local organic egg, double cheddar, caramelized onions, sliced jalapeños, and hickory-smoked BBQ sauce.',
    ingredients: ['Prime Beef Patty', 'Crispy Beef Bacon', 'Fried Organic Egg', 'Double Cheddar', 'Caramelized Onions', 'Jalapeño Peppers', 'BBQ Sauce'],
    calories: '890 kcal',
    protein: '45g',
    carbs: '48g',
    fat: '38g',
    price: 620,
    image: 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?auto=format&fit=crop&q=80&w=800',
    available: true,
    featured: true
  },
  {
    id: '4',
    name: 'Crispy Chicken Burger',
    category: 'chicken-burgers',
    description: 'Generously sized crispy panko-crusted chicken breast, topped with fresh house cabbage coleslaw, melted white cheddar, and rich buttermilk spicy mayonnaise.',
    ingredients: ['Panko-Crusted Chicken Breast', 'House Creamy Coleslaw', 'White Cheddar', 'Brioche Bun', 'Buttermilk Spicy Mayo'],
    calories: '580 kcal',
    protein: '29g',
    carbs: '55g',
    fat: '24g',
    price: 400,
    image: '/src/assets/images/crispy_chicken_burger_1781557851663.jpg',
    available: true,
    featured: false
  },
  {
    id: '5',
    name: 'Chicken Burger',
    category: 'chicken-burgers',
    description: 'Premium flame-grilled marinated chicken patty seasoned with secret local herbs, stacked with crispy lettuce, sliced tomatoes, and our signature herb-infused mayonnaise.',
    ingredients: ['Flame-Grilled Chicken Patty', 'Classic Brioche Bun', 'Iceberg Lettuce', 'Fresh Sliced Tomatoes', 'Signature Herb Mayo'],
    calories: '510 kcal',
    protein: '31g',
    carbs: '39g',
    fat: '18g',
    price: 400,
    image: 'https://images.unsplash.com/photo-1606755962773-d324e0a13086?auto=format&fit=crop&q=80&w=800',
    available: true,
    featured: false
  },
  {
    id: '6',
    name: 'Signature French Fries',
    category: 'fries',
    description: 'Finely selected golden-crust Russet potatoes, triple-cooked for absolute outer crunch and airy center fluffiness, seasoned with sea salt and rosemary dust.',
    ingredients: ['Russet Potatoes', 'Sea Salt', 'Rosemary Herb Dust', 'Served with Herb Garlic Mayo'],
    calories: '320 kcal',
    protein: '4g',
    carbs: '41g',
    fat: '14g',
    price: 180,
    image: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&q=80&w=800',
    available: true,
    featured: false
  },
  {
    id: '7',
    name: 'Loaded Cheese Fries',
    category: 'fries',
    description: 'Our signature crispy golden fries loaded with continuous streams of molten triple-cheese sauce, candied jalapeño, and fresh snippet scallions.',
    ingredients: ['Rosemary French Fries', 'Molten Cheddar Cheese', 'Molten Mozzarella', 'Chive Sprinkles', 'Sweet Candied Jalapeño'],
    calories: '550 kcal',
    protein: '11g',
    carbs: '46g',
    fat: '31g',
    price: 260,
    image: 'https://images.unsplash.com/photo-1585109649139-366815a0d713?auto=format&fit=crop&q=80&w=800',
    available: true,
    featured: true
  },
  {
    id: '8',
    name: 'Belgian Chocolate Milkshake',
    category: 'milkshakes',
    description: 'Decadent imported Belgian dark chocolate blended slowly with rich artisanal house-churned vanilla bean ice cream and premium organic whole milk.',
    ingredients: ['Imported Belgian Dark Chocolate', 'House Vanilla Ice Cream', 'Organic Whole Milk', 'Fresh Whipped Cream', 'Chocolate Ganache Rim'],
    calories: '480 kcal',
    protein: '8g',
    carbs: '58g',
    fat: '18g',
    price: 220,
    image: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&q=80&w=800',
    available: true,
    featured: false
  },
  {
    id: '9',
    name: 'Wild Strawberry Milkshake',
    category: 'milkshakes',
    description: 'A luxurious creamy shake crafted using locally harvested organic Bole strawberries, home-style vanilla custard ice cream, and double-whipped fluff.',
    ingredients: ['Bole Organic Strawberries', 'Vanilla Custard Ice Cream', 'Fresh Milk', 'Double Whipped Cream', 'Strawberry Coulis Drizzle'],
    calories: '460 kcal',
    protein: '7g',
    carbs: '54g',
    fat: '17g',
    price: 240,
    image: 'https://images.unsplash.com/photo-1579954115545-a95591f28bfc?auto=format&fit=crop&q=80&w=800',
    available: true,
    featured: false
  },
  {
    id: '10',
    name: 'Ice Cold Coca-Cola',
    category: 'soft-drinks',
    description: 'Chilled refreshing Coca-Cola can served the premium way: poured over fresh cracked ice with a hand-sliced lemon wheel.',
    ingredients: ['Carbonated Soda Can', 'Lemon Wheel Slice', 'Cracked Crystal Ice'],
    calories: '140 kcal',
    protein: '0g',
    carbs: '39g',
    fat: '0g',
    price: 80,
    image: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&q=80&w=800',
    available: true,
    featured: false
  },
  {
    id: '11',
    name: 'Warm Lava Cake with Gelato',
    category: 'desserts',
    description: 'Rich liquid-center dark chocolate cake baked to order. Served warm alongside a perfectly rounded scoop of Madagascar vanilla bean gelato in a chilled bowl.',
    ingredients: ['Dark Chocolate Fondant', 'Molten Center', 'Madagascar Vanilla Gelato', 'Mint Sprig', 'Powdered Cane Sugar'],
    calories: '520 kcal',
    protein: '6g',
    carbs: '62g',
    fat: '24g',
    price: 280,
    image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&q=80&w=800',
    available: true,
    featured: true
  }
];

export const DEFAULT_SETTINGS: RestaurantSettings = {
  name: 'Wow Burger',
  logo: 'https://img.icons8.com/color/96/burger.png',
  address: 'Bole Road, Behind Edna Mall, Addis Ababa, Ethiopia',
  phone: '+251 911 234 567',
  facebook: 'https://facebook.com/wowburger.addis',
  instagram: 'https://instagram.com/wowburger.addis',
  telegram: 'https://t.me/wowburgeraddis',
  tiktok: 'https://tiktok.com/@wowburger.addis'
};
